# .pre-commit-config.yaml
default_language_version:
  python: python3.14
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0  # Use the latest stable version
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
      - id: mixed-line-ending
  - repo: https://github.com/psf/black
    rev: 24.10.0 # Use the latest stable version
    hooks:
      - id: black
        language_version: python3.14 # Specify your Python version
        exclude: .*migrations\/.*
  - repo: https://github.com/PyCQA/isort
    rev: 5.13.2 # Use the latest stable version
    hooks:
      - id: isort
        name: isort (python)
        args: ["--profile", "black"]
  - repo: https://github.com/PyCQA/flake8
    rev: 7.1.0 # Use the latest stable version
    hooks:
      - id: flake8
        exclude: ^.*/migrations/.*|tuna/settings/api.py
        args: [--max-line-length=120]
